Repository stanford-oval/almond-cloud, pull requests merged in 2019-02, with the labels that each got.

#200 Allow line breaks for messages in web almond conversations
  public/stylesheets/conversation.css
Labels: web almond

#206 Assorted fixes coming from production
  browser/commandpedia.js
  browser/deps/search-or-infinite-scroll.js
  browser/thingpedia-portal.js
  model/schema.js
  public/images/jackiey.jpg
  public/stylesheets/index.css
  public/stylesheets/style.css
  routes/my_api.js
  routes/thingpedia_api.js
  tests/test_thingpedia_api_v3.js
  tests/thingpedia-integration.sh
  tests/webalmond-integration.sh
  tests/website/test_my_api.js
  util/origin.js
  util/secret_key.js
  util/thingpedia-client.js
  views/stanford/about_index.pug
  views/stanford/about_research.pug
  views/stanford/footer.pug
  views/thingpedia_device_create_or_edit.pug
Labels: bug, security

#211 Add Discourse SSO support
  config.js
  package.json
  routes/user.js
  stanford/config.js
  tests/load_test_webalmond.js
  tests/thingpedia-integration.sh
  tests/webalmond-integration.sh
  tests/website/index.js
  tests/website/scaffold.js
  tests/website/test_sso.js
  yarn.lock
Labels: auth

#210 Update transparent-rpc library
  package.json
  routes/devices.js
  routes/devices_compat.js
  routes/my_stuff.js
  routes/status.js
  yarn.lock
Labels: cleanup

#214 Fix bugs noted by lgtm
  .lgtm.yml
  README.md
  almond/enginemanager.js
  frontend.js
  package.json
  public/javascripts/conversation.js
  public/javascripts/profile.js
  routes/my_api.js
  routes/user.js
  scripts/build-doc-index.js
  scripts/count_templates.js
  scripts/migrate_nn_dataset.js
  scripts/migrate_nn_dataset_file.js
  tests/website/test_my_api.js
  util/highlightjs-thingtalk.js
  util/passport.js
  yarn.lock
Labels: bug, cleanup

#209 Making use of Genie
  .travis.yml
  config.js
  package.json
  scripts/augment_dataset.js
  scripts/gen_sentences.js
  scripts/generate_binary_ppdb.js
  scripts/prepare_for_turking.js
  tests/data/tt:short_free_text.txt
  tests/load_test_thingpedia.js
  tests/thingpedia-integration.sh
  training/download-dataset.js
  training/flag_utils.js
  training/replace_parameters.js
  training/training_job.js
  training/update-dataset.js
  util/binary_ppdb.js
  util/ppdb.js
  yarn.lock
Labels: training

#219 Last few fixes from staging
  .travis.yml
  package.json
  training/daemon.js
  training/training_job.js
  yarn.lock
Labels: bug, training

#218 Resurrect a script to process cheatsheet data
  package.json
  scripts/manual_train.js
Labels: training

#223 Advertise our community forum
  README.md
  doc/thingpedia-tutorial.md
  public/images/logo-forum.png
  views/stanford/about_get_involved.pug
  views/stanford/about_research.pug
Labels: content

#226 Fix error handling in Almond API /me/api/parse
  almond/almond_api.js
Labels: bug, error handling
