Repository stanford-oval/almond-cloud, pull requests merged in 2019-08, with the labels that each got.

#370 Bug fixes from staging
  routes/thingpedia_upload.js
  training/daemon.js
  views/thingpedia_device_details.pug
Labels: bug

#376 Add a new API to upload (create/edit) devices
  routes/thingpedia_api.js
  routes/thingpedia_upload.js
  tests/test_thingpedia_api_v3.js
  tests/thingpedia-integration.sh
  util/errors.js
  util/import_device.js
  util/validation.js
Labels: dev_experience, enhancement, thingpedia

#380 Actually apply weekly credit updates
  almond-credit-update.service
  almond-credit-update.timer
  model/migrations/15af11d-org_credit_updates.sql
  model/organization.js
  model/schema.sql
  routes/developer_console.js
  scripts/apply-credits.js
  util/credit_system.js
Labels: dev_experience

#382 Pass over those pesky LGTM alerts
  frontend.js
  model/schema.sql
  package.json
  routes/developer_oauth2.js
  routes/doc.js
  routes/my_api.js
  routes/my_conversation.js
  routes/my_internal_api.js
  routes/my_oauth2.js
  scripts/bootstrap.js
  scripts/cleanup-userdb.js
  scripts/count_templates.js
  scripts/manual_train.js
  scripts/migrate_nn_dataset_file.js
  tests/website/test_my_api.js
  tests/website/test_oauth.js
  tests/website/test_register.js
  util/code_storage.js
  util/oauth2.js
  util/validation.js
  views/dev_oauth.pug
  views/my_conversation.pug
  views/my_stuff.pug
  views/oauth2_authorize.pug
  views/stanford/about_get_almond.pug
  views/user_profile.pug
  yarn.lock
Labels: bug, cleanup

#384 Part 2 of the Alexa skill builder prototype
  frontend.js
  model/alexa_model.js
  model/schema.sql
  public/javascripts/device-selector.js
  public/stylesheets/thingpedia.css
  routes/developer_alexa.js
  routes/developer_console.js
  tests/load_test_thingpedia.js
  util/dataset.js
  views/dev_alexa.pug
  views/dev_alexa_model.pug
  views/dev_nlp_models.pug
  views/dev_sidebar.pug
  views/device_selector.pug
Labels: dev_experience

#385 Small bug fixes
  almond/enginemanagerclient.js
  almond/master.js
  routes/status.js
  tests/website/test_admin.js
  views/dev_sidebar.pug
  views/status.pug
  yarn.lock
Labels: bug

#395 Some training-related bug fixes
  model/alexa_model.js
  model/migrations/a3f600e-users_developer_model.sql
  model/migrations/a8dd900-model_contextual_flag.sql
  model/nlp_models.js
  model/schema.sql
  model/template_files.js
  routes/admin.js
  routes/developer_alexa.js
  routes/developer_console.js
  routes/luinet_models.js
  routes/luinet_templates.js
  routes/user.js
  scripts/bootstrap.js
  tests/nlp-integration.sh
  tests/thingpedia-integration.sh
  training/daemon.js
  training/sandboxed_synthetic_gen.js
  util/i18n.js
  util/user.js
Labels: bug, training

#396 More bug fixes from staging
  model/template_files.js
  package.json
  scripts/bootstrap.js
  tests/thingpedia-integration.sh
  training/sandboxed_synthetic_gen.js
  training/update-dataset.js
  yarn.lock
Labels: bug, training

#365 aws kubernetes for training
  config.js
  doc/almond-config-file-reference.md
  nlp/admin.js
  production/base/alb-ingress-controller/aim-policy.json
  production/base/alb-ingress-controller/alb-ingress-controller.yaml
  production/base/alb-ingress-controller/node-trust-policy.json
  production/base/alb-ingress-controller/rbac-role.yaml
  production/base/docker/Dockerfile
  production/base/external-dns/external-dns.yaml
  production/base/external-dns/node-trust-policy.json
  production/base/external-dns/route53-policy.json
  production/base/kube2iam/kube2iam-policy.json
  production/base/kube2iam/rbac-config.yaml
  production/base/kube2iam/values-kube2iam.yaml
  production/nlp/docker/Dockerfile
  production/nlp/docker/config_get.js
  production/nlp/docker/startup.sh
  production/nlp/k8/deployment.yaml
  production/nlp/k8/ingress.yaml
  production/nlp/k8/service.yaml
  production/tokenizer/Dockerfile
  production/training/docker/Dockerfile
  production/training/docker/startup.sh
  production/training/docker/training.conf.json
  production/training/docker/training_small.conf.json
  production/training/k8/deployment.yaml
  production/training/k8/gpu-deployment.yaml
  production/training/k8/ingress.yaml
  production/training/k8/service.yaml
  training/gpu_training_daemon.js
  training/gpu_training_job.js
  training/training_job.js
  util/command.js
Labels: performance

#399 A fix to the kubernetes-based training server
  production/nlp/k8/ingress.yaml
  production/training/k8/ingress.yaml
  training/gpu_training_job.js
Labels: bug

#402 Last minute bugfixes
  routes/mturk.js
  util/device_factories.js
  views/dev_alexa.pug
  views/dev_nlp_models.pug
  views/dev_sidebar.pug
  views/layout.pug
  views/mturk-submit.pug
  views/register_success.pug
Labels: bug

#409 Urgent fixes for NLP inference
  nlp/nlp_model.js
Labels: bug

#443 training: typecheck the whole dataset
  training/prepare-training-set.js
  training/update-dataset.js
Labels: bug

#444 Dataset uploading issues
  tests/test_thingpedia_api_v3.js
  tests/website/test_string_entities.js
  util/upload_dataset.js
Labels: bug

#447 Stricter validation rules for IDs
  routes/developer_alexa.js
  routes/luinet_models.js
  routes/luinet_templates.js
  util/errors.js
  util/upload_dataset.js
  util/user.js
  util/validation.js
Labels: cleanup, security

#452 validation: wrap errors from ThingTalk
  util/validation.js
Labels: bug

#449 frontend: move static assets to the /assets URL
  config.js
  frontend.js
  tests/nlp-integration.sh
  tests/thingpedia-integration.sh
  tests/webalmond-integration.sh
  util/code_storage.js
Labels: cleanup, content

#445 Fix training of models by tag
  model/nlp_models.js
Labels: bug

#442 Fix some problems in the exact matcher
  model/migrations/4b93ac8-models_use_exact.sql
  model/schema.sql
  nlp/admin.js
  nlp/exact.js
  nlp/main.js
  nlp/nlp_model.js
  routes/luinet_models.js
  scripts/bootstrap.js
  views/dev_nlp_models.pug
Labels: bug, nlp inference

#446 training: mark evaluation candidate examples correctly
  package.json
  tests/thingpedia-integration.sh
  training/prepare-training-set.js
  yarn.lock
Labels: bug
